name: 'Concatenate files'
description: 'This action creates a file by concatenating the specified files.'
author: 'nikkie'
inputs:
  sources:
    description: 'A string which represents paths of concatenated files.'
    required: true
  destination:
    description: 'Path to the created file.'
    required: true
runs:
  using: composite
  steps:
  - run: |
      ${GITHUB_ACTION_PATH}/entrypoint.sh ${SOURCES} ${DESTINATION}
    env:
      # workaround ref: https://github.com/actions/runner/issues/665#issuecomment-699481628
      SOURCES: ${{ inputs.sources }}
      DESTINATION: ${{ inputs.destination }}
    shell: bash
branding:
  icon: 'file-text'
  color: 'green'
