name: Doctest series of files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Prepare doctest target file
        uses: ftnext/action-concatenate-files@main
        with:
          sources: example/item_ham.rst.txt example/item_spam.rst.txt
          destination: example/doctest_target.rst.txt
      - name: Run doctest
        run: python -m doctest -v example/doctest_target.rst.txt
